from app.models.instituciones import Institucion
from app.models.usuarios import Usuario
from app.models.deportes import Deporte
from app.models.club_equipo import ClubEquipo
from app.models.atleta_jugador import AtletaJugador
from app.models.torneos import Torneo
from app.models.grupos import Grupo
from app.models.inscripciones import Inscripcion
from app.models.sedes import Sede
from app.models.fixture import Fixture
from app.models.partidos import Partido
from app.models.eventos_partido import EventoPartido
from app.models.auditoria import Auditoria
from app.models.noticias import Noticia
from app.models.notificaciones import Notificacion
